name: Build and Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: mkdir out

      - name: build
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --standalone
            --slide-level=2
            -t revealjs
            --output=out/index.html
            --self-contained
            slides.md

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: out
